version: "3.7"
services:
  db:
    build:
      context: .
    ports:
      - "4321:4321"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - './queries:/queries'
